name: UserAdvocate
favicon: null
layout_spectrum: 0.8907014599535614
typography_spectrum: 0.9225834596436471
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.4961136293131858
  lightness: 0.657163237920031
  saturation: 0.24518362642265856
  rhythmicContrast: 0.3249012266751379
purpose: []
