title: Digital Transformation  & Brand Development
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.3972431
  brandStrength: 0.375
  lightness: 0.3189223
  brandColors:
    - '#47667B'
    - '#DCB498'
    - '#B56447'
    - '#969EA0'
    - '#241F1C'
  rhythmicContrast: 0.7788221
cta:
  bucket: null
  version: null
  domain: null
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
name: UserAdvocate
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.1509275
layout_spectrum: 1
